[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.16.0"

hooks = [
  { id = "ruff-check", args = ["--fix"] },
  
  { id = "ruff-format" }
]

[[repos]]
repo = "https://github.com/astral-sh/ty-pre-commit"
rev = "v0.0.61"
hooks = [
  { id = "ty" }
]