[tool.ruff]
line-length = 80

# Target Python version
target-version = "py314"

[tool.ruff.lint]
select = [
  "E", "F", 
  "D", # Enable docstring checks
]

extend-select = [
  "SLF", # flake8-self (private-member-access)
  "ANN", # flake8-annotations: Enforce type annotations on functions
]

ignore = [
  "D100", # Missing docstring in public module
  "D104", # Missing docstring in public package
  "D107", # Missing docstring in __init__
  "ANN101", # Missing type annotation for 'self' in methods
  "ANN102", # Missing type annotation for 'cls' in classmethods
  "D417", # Missing argument description in docstring (makes parameter docs optional!)
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.uv.workspace]
members = [
    "examples/gcc",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mkbuild"
version = "0.1.1"
description = "A build system scripting service"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.16.0",
    "ty>=0.0.63",
]

