from mkbuild.compiler import Compiler
from mkbuild.hash_handler import HashHandler
from mkbuild.linker import Linker
from mkbuild.sources import Sources
from mkbuild.transformer import Transformer


class Pipe:
    """A single transform step in the pipeline."""

    def __init__(
        self, hash_handler: HashHandler, transformer: Transformer
    ) -> None:
        self.transformer = transformer
        self.hash_handler = hash_handler

    def run(self, raw_sources: list[str] | None = None) -> list[str] | None:
        """Process sources with transformer and hash changes.

        Args:
            raw_sources: Optional raw sources from the previous pipe.

        Returns:
            The target sources generated by this pipe.
        """
        match self.transformer.ACCEPT:
            case "previous":
                sources = Sources(self.transformer, raw_sources)
            case "all":
                sources = Sources(self.transformer)
            case "previous-changed":
                sources = self.hash_handler.get_changed_sources(
                    Sources(self.transformer, raw_sources)
                )
            case "changed":
                sources = self.hash_handler.get_changed_sources(
                    Sources(self.transformer)
                )
        if (
            self.transformer.ACCEPT in ("changed", "previous-changed")
            and sources.is_empty
        ):
            return

        if isinstance(self.transformer, Compiler):
            for source, target in zip(sources.sources, sources.targets):
                self.transformer.transform(source, target)

        elif isinstance(self.transformer, Linker):
            self.transformer.transform(list(sources.sources), None)

        return list(sources.targets)
