from mk.compiler import Compiler
from mk.context import Context
from mk.hash_handler import HashHandler
from mk.linker import Linker
from mk.sources import Sources
from mk.transformer import Transformer


class Pipe:
    """A single transform step in the pipeline."""

    def __init__(
        self, ctx: Context, hash_handler: HashHandler, transformer: Transformer
    ) -> None:
        self.ctx = ctx
        self.transformer = transformer
        self.hash_handler = hash_handler

    def run(self, raw_sources: list[str] | None = None) -> list[str]:
        """Process sources with transformer and hash changes.

        Args:
            raw_sources: Optional raw sources from the previous pipe.

        Returns:
            The target sources generated by this pipe.
        """
        sources = Sources(self.ctx, self.transformer, raw_sources)
        changed_sources = self.hash_handler.get_changed_sources(sources)

        if isinstance(self.transformer, Compiler):
            for source, target in zip(
                changed_sources.sources, changed_sources.targets
            ):
                self.transformer.transform(self.ctx, source, target)

        elif isinstance(self.transformer, Linker):
            self.transformer.transform(
                self.ctx, list(changed_sources.sources), None
            )

        return list(sources.targets)
